// Generated by design/build.py from design/kit/. Do not edit by hand.

export declare class NxWindow extends HTMLElement {
  acceptDrops(...args: any[]): any;
  addResizer(...args: any[]): any;
  build(...args: any[]): any;
  close(...args: any[]): any;
  open(...args: any[]): any;
  place(...args: any[]): any;
  raise(...args: any[]): any;
  rename(...args: any[]): any;
  save(...args: any[]): any;
  wire(...args: any[]): any;
  [held: string]: any;
}

export declare class NxMenu extends HTMLElement {
  close(...args: any[]): any;
  openAt(...args: any[]): any;
  showFor(...args: any[]): any;
  [held: string]: any;
}

export declare class NxMenuItem extends HTMLElement {
  [held: string]: any;
}

export declare class NxDock extends HTMLElement {
  aimAt(...args: any[]): any;
  arrange(...args: any[]): any;
  carry(...args: any[]): any;
  isFree(...args: any[]): any;
  settle(...args: any[]): any;
  slotOf(...args: any[]): any;
  slotUnder(...args: any[]): any;
  [held: string]: any;
}

export declare class NxTile extends HTMLElement {
  [held: string]: any;
}

export declare class NxFloor extends HTMLElement {
  show(...args: any[]): any;
  tile(...args: any[]): any;
  [held: string]: any;
}

export declare class NxScroller extends HTMLElement {
  addBar(...args: any[]): any;
  drive(...args: any[]): any;
  fit(...args: any[]): any;
  refresh(...args: any[]): any;
  [held: string]: any;
}

export declare class NxShelf extends HTMLElement {
  choose(...args: any[]): any;
  [held: string]: any;
}

export declare class NxThing extends HTMLElement {
  attributeChangedCallback(...args: any[]): any;
  carry(...args: any[]): any;
  [held: string]: any;
}

export declare class NxAsk extends HTMLElement {
  ask(...args: any[]): any;
  askFor(...args: any[]): any;
  close(...args: any[]): any;
  tell(...args: any[]): any;
  [held: string]: any;
}

export declare class NxViewer extends HTMLElement {
  arrow(...args: any[]): any;
  show(...args: any[]): any;
  thing(...args: any[]): any;
  [held: string]: any;
}

export declare class NxSlider extends HTMLElement {
  draw(...args: any[]): any;
  drawTheTicks(...args: any[]): any;
  land(...args: any[]): any;
  reachFor(...args: any[]): any;
  wire(...args: any[]): any;
  [held: string]: any;
}

export declare const DESK_WAS_NEW: any;
export declare const FLIGHT_MS: any;
export declare const GRIP_PX: any;
export declare const NEAR_FLIGHT_MS: any;
export declare const STORE: any;
export declare const SVG_NS: any;
export declare const WAYS: any;
export declare const ZOOM_MS: any;
export declare const ZOOM_RECTANGLES: any;
export declare const between: any;
export declare const defineTheKit: any;
export declare const deskIsNew: any;
export declare const deskPoint: any;
export declare const deskRect: any;
export declare const deskRoom: any;
export declare const deskScale: any;
export declare const draggable: any;
export declare const fly: any;
export declare const gatherWindows: any;
export declare const gesture: any;
export declare const onDesk: any;
export declare const readState: any;
export declare const recall: any;
export declare const remember: any;
export declare const restoreFront: any;
export declare const setDeskScale: any;
export declare const showArt: any;
export declare const stillness: any;
export declare const zoom: any;

declare global {
  interface HTMLElementTagNameMap {
    "nx-window": NxWindow;
    "nx-menu": NxMenu;
    "nx-menu-item": NxMenuItem;
    "nx-dock": NxDock;
    "nx-tile": NxTile;
    "nx-floor": NxFloor;
    "nx-scroller": NxScroller;
    "nx-shelf": NxShelf;
    "nx-thing": NxThing;
    "nx-ask": NxAsk;
    "nx-viewer": NxViewer;
    "nx-slider": NxSlider;
  }
}
