/* The NeXTSTEP kit: everything the interface is built from.
 *
 * Generated by design/build.py from design/kit/. Do not edit by hand.
 *
 * Each part is one source in design/kit/, holding its element and its
 * styles together:
 *
 *   base                   the tokens, the reset and the two edges
 *   desk                   what the desk remembers, and the gestures
 *   nx-window              a frame that drags, resizes, closes and remembers
 *   nx-menu, nx-menu-item  the menu, and the entries that open windows
 *   nx-tile, nx-floor      the strip of tiles, and the floor the others stand on
 *   nx-scroller            a view with NeXT's scroller on its left
 *   nx-shelf, nx-thing     a floor of icons, one of which may be chosen
 *   nx-ask                 the panel that asks before a change
 *   nx-viewer              the File Viewer, as four bands in one window
 *   panel                  nx-portrait, nx-row and nx-field, for an info panel
 *   terminal               a text view, black on white
 *
 * They use the light DOM rather than a shadow root, so the stylesheet
 * reaches them and the design tokens carry through.
 */

const SVG_NS = "http://www.w3.org/2000/svg";
const STORE = "nextstep-workspace:v4";

/* --- what the desk remembers -------------------------------------------- */

/** @returns {object} Everything saved about the desk, or an empty record. */
function readState() {
  try { return JSON.parse(localStorage.getItem(STORE)) ?? {}; }
  catch { return {}; }
}

/**
 * Writes one element's state, leaving every other one untouched.
 * @param {string} name - What the element calls itself.
 * @param {object} state - The keys to merge in.
 */
function remember(name, state) {
  const all = readState();
  all[name] = { ...(all[name] ?? {}), ...state };
  localStorage.setItem(STORE, JSON.stringify(all));
}

/** @param {string} name @returns {object} That element's saved state. */
function recall(name) {
  return readState()[name] ?? {};
}

/**
 * Points an element at one of the pictures build.py baked into the stylesheet.
 * @param {HTMLElement} el
 * @param {string} name - The picture's name, which is its file's stem.
 */
function showArt(el, name) {
  el.style.backgroundImage = "var(--" + name + ")";
}

/**
 * Runs a pointer gesture and reports the result when it ends.
 * @param {HTMLElement} handle - Where the gesture starts.
 * @param {(event: PointerEvent, start: object) => void} onMove
 * @param {(event: PointerEvent) => object} onStart - Whatever the mover needs
 *   to know about the moment the gesture began.
 * @param {(start: object) => void} [onEnd] - Given what onStart returned,
 *   which by then carries whatever the moves wrote into it.
 */
function gesture(handle, onMove, onStart, onEnd) {
  handle.addEventListener("pointerdown", (event) => {
    event.stopPropagation();
    /* Without this the browser starts its own text selection under the
       pointer, and dragging a window paints half the desk blue. */
    event.preventDefault();
    handle.setPointerCapture(event.pointerId);
    const start = onStart(event);

    /* A pointer reports faster than the screen redraws, so the moves are
       coalesced into one update per frame. Everything beyond the last one in
       a frame is work whose result is painted over before anybody sees it. */
    let latest = null;
    let frame = 0;

    const apply = () => {
      frame = 0;
      onMove(latest, start);
    };

    const move = (moveEvent) => {
      latest = moveEvent;
      if (!frame) frame = requestAnimationFrame(apply);
    };

    const finish = () => {
      handle.removeEventListener("pointermove", move);
      /* The last position has to land before anything saves it, so a frame
         still owed is run now rather than cancelled. */
      if (frame) {
        cancelAnimationFrame(frame);
        apply();
      }
      onEnd?.(start);
    };

    handle.addEventListener("pointermove", move);
    handle.addEventListener("pointerup", finish, { once: true });
    handle.addEventListener("pointercancel", finish, { once: true });
  });
}

/**
 * Moves an element by its handle, and settles it where it was let go.
 *
 * Whilst the gesture runs the element is moved with a transform, which the
 * compositor can do without laying the page out again. Its left and top are
 * written once, at the end, so everything that reads them afterwards sees a
 * plain position and knows nothing about how it got there.
 *
 * @param {HTMLElement} element - What moves.
 * @param {HTMLElement} handle - What is grabbed.
 * @param {object} hooks
 * @param {() => void} [hooks.onGrab] - Called as the gesture begins.
 * @param {() => void} [hooks.onSettled] - Called once the position is written.
 */
function draggable(element, handle, { onGrab, onSettled } = {}) {
  gesture(handle,
    (event, start) => {
      /* Never past the top or left edge, and never wholly behind the dock. */
      start.left = Math.max(0, Math.min(event.clientX - start.grabX, innerWidth - 90));
      start.top = Math.max(0, Math.min(event.clientY - start.grabY, innerHeight - 24));
      element.style.transform =
        `translate(${start.left - start.fromLeft}px, ${start.top - start.fromTop}px)`;
    },
    (event) => {
      onGrab?.();
      const fromLeft = element.offsetLeft;
      const fromTop = element.offsetTop;
      return {
        grabX: event.clientX - fromLeft, grabY: event.clientY - fromTop,
        fromLeft, fromTop, left: fromLeft, top: fromTop,
      };
    },
    (start) => {
      element.style.transform = "";
      element.style.left = start.left + "px";
      element.style.top = start.top + "px";
      onSettled?.();
    });
}

/* --- the desk is not a document ------------------------------------------

   A right click here opens what the thing under the pointer offers, or
   nothing. The browser's own menu is about a document: reload it, save the
   picture, look at the source. None of that is about a machine or a window,
   and NeXTSTEP never put anything of the sort on a desk.

   Refused for the whole desk, including the fields and anything a terminal
   will hold, because one rule that holds everywhere is the only kind a person
   can rely on. What has a menu of its own opens it from its own handler. */
addEventListener("contextmenu", (event) => event.preventDefault());

/* --- the desk does not hold text -----------------------------------------

   user-select says a selection may not begin inside an element. It does not
   stop a browser that begins one anyway, and a drag across a shelf then leaves
   every label it passed highlighted in the browser's own blue.

   Refused here rather than in a stylesheet, because this holds whatever the
   browser makes of the property. A terminal is the exception: reading
   something out of it is the point of having one. */
addEventListener("selectstart", (event) => {
  if (!event.target.closest?.(".terminal")) event.preventDefault();
});

/* --- the letters beside the menu entries ---------------------------------

   NeXTSTEP drew those for Command key shortcuts. Command and Control both
   belong to the browser here, so the letter acts on its own, and three
   conditions keep that from being a nuisance: nothing held down, nothing being
   typed into, and no panel up, because a panel has a keyboard of its own and
   two answers to give with it.

   A context menu is left out. Its entries act on whatever was right clicked,
   and a key press has nothing under the pointer. */
addEventListener("keydown", (event) => {
  if (event.metaKey || event.ctrlKey || event.altKey) return;
  if (document.querySelector("nx-ask[data-open]")) return;

  const focused = document.activeElement;
  if (focused?.matches?.("input, textarea, select") || focused?.isContentEditable) return;

  const pressed = event.key.toLowerCase();
  const item = [...document.querySelectorAll("nx-menu:not([context]) nx-menu-item[key]")]
    .find((entry) => entry.getAttribute("key").toLowerCase() === pressed);
  if (!item || item.hasAttribute("disabled")) return;

  event.preventDefault();
  item.click();
});

/**
 * Puts the front window back in front and every other one behind it.
 *
 * This runs over all the windows rather than inside any one of them, because
 * being in front is a statement about all of them together: a window can only
 * make itself active by making the others inactive, and at a load none of them
 * has done that yet. Without it every title bar is drawn active, which is a
 * desk NeXTSTEP never showed.
 *
 * Without a remembered name the last open window in the markup takes it, which
 * is the one a reader would call the frontmost.
 */
function restoreFront() {
  const windows = [...document.querySelectorAll("nx-window")];
  for (const window_ of windows) window_.setAttribute("inactive", "");
  const remembered = recall("desk").front;
  const open = windows.filter((window_) => !window_.hidden);
  const front = open.find((window_) => window_.name === remembered) ?? open.at(-1);
  front?.raise();
}

/* --- pictures of things moving -------------------------------------------

   Two of them, and both are pictures rather than the things themselves: an
   icon on its way to the floor of the screen, and the way from a folder to
   the place its contents will appear. Neither is asked about by anything: a
   caller says where from and where to, and waits for it to land. */

/** How long an icon takes to reach its place on the floor. Brisk, because it
 *  is a thing moving rather than an effect: long enough to be followed by the
 *  eye and short enough that anybody waits for it. */
const FLIGHT_MS = 260;

/** The same inside one window, where the way is a fraction as long. A hundred
 *  pixels crossed at the speed of half a screen reads as hesitant, so a short
 *  way is given a short time. */
const NEAR_FLIGHT_MS = 130;

/** How many rectangles the way is drawn with, and over how long. Few and
 *  fast: what is wanted is a run of outlines standing on the screen for a
 *  moment, not a box growing. */
const ZOOM_RECTANGLES = 8;
const ZOOM_MS = 200;

/** @returns {boolean} Whether the reader has asked for less movement. */
function stillness() {
  return matchMedia("(prefers-reduced-motion: reduce)").matches;
}

/**
 * Sends a picture of an icon from one place to another.
 * @param {string} icon - Which picture.
 * @param {DOMRect} from - Where it starts.
 * @param {DOMRect} to - Where it lands.
 * @param {number} howLong - How long it takes, in milliseconds. The default
 *   is the way across the screen; a way inside one window is shorter and is
 *   given NEAR_FLIGHT_MS.
 * @returns {Promise} Settled when it has landed.
 *
 * A transform and nothing else, so this costs the compositor and not the
 * layout. Where the reader has asked for less movement there is no flight at
 * all: the tile is simply there, which is what they asked for.
 */
function fly(icon, from, to, howLong = FLIGHT_MS) {
  if (stillness()) return Promise.resolve();

  const ghost = document.createElement("i");
  ghost.className = "art flying";
  showArt(ghost, icon);
  ghost.style.left = to.left + "px";
  ghost.style.top = to.top + "px";
  ghost.style.width = to.width + "px";
  ghost.style.height = to.height + "px";
  document.body.append(ghost);

  const across = (from.left + from.width / 2) - (to.left + to.width / 2);
  const down = (from.top + from.height / 2) - (to.top + to.height / 2);
  const smaller = to.width ? Math.max(0.2, from.width / to.width) : 1;

  const flight = ghost.animate([
    { transform: `translate(${across}px, ${down}px) scale(${smaller})` },
    { transform: "translate(0, 0) scale(1)" },
  ], { duration: howLong, easing: "ease-out" });

  return flight.finished.catch(() => {}).finally(() => ghost.remove());
}



/**
 * Draws the way from one place to another, as a run of rectangles.
 * @param {DOMRect} from - Where it starts, which is the mark around an icon.
 * @param {DOMRect} to - Where it ends, which is the box about to hold what
 *   was in that folder.
 * @returns {Promise} Settled when they have gone.
 *
 * Several, and none of them is rubbed out: each is drawn at its own size a
 * moment after the last, so what stands on the screen is a run of nested
 * outlines from the icon to the band, and they all go together at the end.
 * That is what makes it read as a wave rather than as one box growing.
 *
 * Outlines rather than filled rectangles, because filled ones would be a
 * black flash across half the window.
 */
function zoom(from, to) {
  if (stillness()) return Promise.resolve();

  const drawn = [];
  let last = null;
  for (let step = 1; step <= ZOOM_RECTANGLES; step += 1) {
    const part = step / ZOOM_RECTANGLES;
    const box = document.createElement("div");
    box.className = "zooming";
    box.style.left = between(from.left, to.left, part) + "px";
    box.style.top = between(from.top, to.top, part) + "px";
    box.style.width = between(from.width, to.width, part) + "px";
    box.style.height = between(from.height, to.height, part) + "px";
    box.style.opacity = "0";
    document.body.append(box);
    drawn.push(box);

    /* Turned on rather than faded in: a rectangle is there or it is not. */
    last = box.animate([{ opacity: 0 }, { opacity: 1 }], {
      duration: 1,
      delay: (step - 1) * (ZOOM_MS / ZOOM_RECTANGLES),
      fill: "forwards",
    });
  }

  return last.finished
    .catch(() => {})
    .finally(() => drawn.forEach((box) => box.remove()));
}

/**
 * @param {number} start
 * @param {number} end
 * @param {number} part - Where between them, from zero to one.
 * @returns {number} Rounded, because a rectangle drawn on half a pixel is a
 *   grey line rather than a black one.
 */
function between(start, end, part) {
  return Math.round(start + (end - start) * part);
}

/* --- nx-window ---------------------------------------------------------- */

/**
 * A window: title bar, close button, optional resize bar, and a memory.
 *
 * It writes its position, its size and whether it is open under its name, so
 * the desk comes back the way it was left. A window marked `fixed` has no
 * resize bar, one marked `flush` lets its content run to the frame, and one
 * marked `drop` accepts things dragged onto it.
 *
 * @attr name   - What it is called in storage and to the menu. Required.
 * @attr title  - The text in the bar.
 * @attr x y w h - Where it starts, before anything was remembered.
 * @attr min-w min-h - The floor its content needs.
 */
class NxWindow extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const content = [...this.childNodes];
    this.replaceChildren();

    this.bar = this.build("div", "titlebar");
    this.bar.append(this.build("i", "art wbtn mini"));
    const title = this.build("div", "title");
    title.textContent = this.getAttribute("title") ?? "";
    this.removeAttribute("title");         /* or the browser shows a tooltip */
    const close = this.build("i", "art wbtn close");
    this.bar.append(title, close);

    this.pane = this.build("div", "pane");
    this.pane.append(...content);
    this.append(this.bar, this.pane);

    if (!this.hasAttribute("fixed")) this.addResizer();
    if (this.hasAttribute("drop")) this.acceptDrops();
    this.place();
    this.wire(close);
  }

  /**
   * Puts a different name in the title bar.
   * @param {string} text - What the window is about now.
   *
   * For a window that says something about whatever was chosen, where the
   * name is the difference between two of them.
   */
  rename(text) {
    const title = this.bar?.querySelector(".title");
    if (title) title.textContent = text;
  }

  /** @returns {HTMLElement} A child element, appended nowhere yet. */
  build(tag, className) {
    const el = document.createElement(tag);
    el.className = className;
    return el;
  }

  /** Puts the window where it was left, or where its attributes say. */
  place() {
    const saved = recall(this.name);
    const number = (key, attribute) => saved[key] ?? Number(this.getAttribute(attribute));
    /* A window nobody can resize has no size of its own to remember, so its
       markup decides. Otherwise a size saved before it was fixed, or before
       its contents changed, would outlive both. */
    const fixed = this.hasAttribute("fixed");
    const size = fixed
      ? (_key, attribute) => Number(this.getAttribute(attribute))
      : number;

    this.style.left = Math.min(number("x", "x"), Math.max(0, innerWidth - 90)) + "px";
    this.style.top = Math.min(number("y", "y"), Math.max(0, innerHeight - 40)) + "px";

    /* Before the size, because the floor is read off these and a size saved
       when the window held something else has to be held to what it holds
       now. */
    for (const [attribute, property] of [["min-w", "--win-min-w"], ["min-h", "--win-min-h"]]) {
      if (this.hasAttribute(attribute)) {
        this.style.setProperty(property, this.getAttribute(attribute) + "px");
      }
    }
    const floor = this.floor;

    this.style.width = Math.max(size("w", "w"), floor.width) + "px";

    /* A fixed window is as tall as what is in it, unless its markup says
       otherwise. A height written by hand is a number that stops being right
       the moment a row is added, and both windows here had drifted that way.
       Width stays a decision, because a column of readings has no natural
       one. */
    this.style.height = fixed && !this.hasAttribute("h")
      ? "auto"
      : Math.max(size("h", "h"), floor.height) + "px";
    /* A window is open unless it says otherwise, and what was remembered
       beats what the markup starts it at. */
    this.hidden = !(saved.open ?? !this.hasAttribute("closed"));
  }

  /** @returns {string} The name it is known by. */
  get name() { return this.getAttribute("name"); }

  /** The floor this window's content needs, read off the element itself. */
  get floor() {
    const style = getComputedStyle(this);
    return {
      width: parseInt(style.getPropertyValue("--win-min-w"), 10),
      height: parseInt(style.getPropertyValue("--win-min-h"), 10),
    };
  }

  /**
   * Saves whether it is open, and where and how big it is.
   *
   * A hidden element measures zero on every side, so a closed window keeps the
   * geometry it had rather than writing that over with nothing. Otherwise it
   * would come back in the corner at no size at all.
   */
  save() {
    const state = { open: !this.hidden };
    if (!this.hidden) {
      Object.assign(state, {
        x: this.offsetLeft, y: this.offsetTop,
        w: this.offsetWidth, h: this.offsetHeight,
      });
    }
    remember(this.name, state);
  }

  /**
   * Brings it forward and pushes every other window back. Which window is in
   * front is part of what the desk remembers, because exactly one is active at
   * a time and a reload that made them all active would be a desk nobody has
   * ever seen.
   */
  raise() {
    if (!this.hasAttribute("inactive") && this.style.zIndex) return;
    let highest = 10;
    for (const other of document.querySelectorAll("nx-window")) {
      highest = Math.max(highest, Number(other.style.zIndex) || 10);
      other.setAttribute("inactive", "");
    }
    this.style.zIndex = highest + 1;
    this.removeAttribute("inactive");
    remember("desk", { front: this.name });
  }

  /**
   * Shows it, in front.
   * @param {HTMLElement} [asker] - What was used to open it, if anything was.
   *   It rides along as a rectangle, because an application whose icon has to
   *   travel to the foot of the screen has to know where it is travelling
   *   from, and only whoever was clicked knows that.
   */
  open(asker) {
    this.hidden = false;
    this.raise();
    this.save();
    /* So whatever fills this window can fill it now rather than at the next
       poll, which is up to five seconds of dashes. */
    this.dispatchEvent(new CustomEvent("nx-open", {
      bubbles: true,
      detail: { from: asker?.getBoundingClientRect?.() ?? null },
    }));
  }

  /** Hides it, keeping its geometry for the next time.
   *
   * Says so as it goes, because what a window holds may be more than a
   * drawing: a session on the other side of a socket has to be told that
   * nobody is looking any more.
   */
  close() {
    this.hidden = true;
    this.save();
    this.dispatchEvent(new CustomEvent("nx-close", { bubbles: true }));
  }

  /**
   * Takes what is dropped on it, and says so whilst something is over it.
   *
   * Raises the same `nx-choose` a double click does, because carrying a thing
   * here and double clicking it mean the same thing to whoever answers.
   */
  acceptDrops() {
    this.addEventListener("dragover", (event) => {
      event.preventDefault();
      event.dataTransfer.dropEffect = "copy";
      this.setAttribute("droppable", "");
    });

    /* Moving onto a child fires dragleave on the parent, so only a pointer
       that has actually left the window counts. */
    this.addEventListener("dragleave", (event) => {
      if (!this.contains(event.relatedTarget)) this.removeAttribute("droppable");
    });

    this.addEventListener("drop", (event) => {
      event.preventDefault();
      this.removeAttribute("droppable");
      this.dispatchEvent(new CustomEvent("nx-choose", {
        bubbles: true,
        detail: { value: event.dataTransfer.getData("text/plain") },
      }));
    });
  }

  /** The bar along the foot: a middle that takes the height and two ends that
   *  take the corner with it. */
  addResizer() {
    const bar = this.build("div", "resizer");
    const left = this.build("div", "end");
    const right = this.build("div", "end");
    left.dataset.corner = "left";
    right.dataset.corner = "right";
    bar.append(left, this.build("div", "middle"), right);
    this.append(bar);

    for (const handle of bar.children) {
      const corner = handle.dataset.corner;
      gesture(handle,
        (event, start) => {
          const floor = this.floor;
          this.style.height = Math.max(floor.height, start.height + event.clientY) + "px";
          if (corner === "right") {
            this.style.width = Math.max(floor.width, start.width + event.clientX) + "px";
          } else if (corner === "left") {
            /* Dragging the left end moves that edge and holds the right one
               still, so the two have to change together. */
            const left = Math.min(event.clientX - start.grabX, start.right - floor.width);
            this.style.left = left + "px";
            this.style.width = (start.right - left) + "px";
          }
        },
        (event) => {
          this.raise();
          return {
            width: this.offsetWidth - event.clientX,
            height: this.offsetHeight - event.clientY,
            grabX: event.clientX - this.offsetLeft,
            right: this.offsetLeft + this.offsetWidth,
          };
        },
        () => this.save());
    }
  }

  /** Dragging by the bar, closing by the button, raising by a click anywhere. */
  wire(close) {
    draggable(this, this.bar, {
      onGrab: () => this.raise(),
      onSettled: () => this.save(),
    });

    close.addEventListener("click", (event) => {
      event.stopPropagation();
      this.close();
    });
    /* The bar's own gesture would otherwise start a drag from the button, and
       the window would follow the pointer as it closed. */
    close.addEventListener("pointerdown", (event) => event.stopPropagation());

    this.addEventListener("pointerdown", () => this.raise());
  }
}

/* --- nx-menu ------------------------------------------------------------ */

/**
 * The menu: a title that drags the whole thing, and entries beneath it.
 * @attr name - What it is called in storage.
 * @attr title - The text in its black bar.
 * @attr x y - Where it starts.
 */
class NxMenu extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const title = document.createElement("div");
    title.className = "title";
    title.textContent = this.getAttribute("title") ?? "";
    this.removeAttribute("title");
    this.prepend(title);

    /* Whether to keep a column for pictures is the menu's decision and not
       each entry's: the words line up when every entry holds the place, and a
       menu where nothing has a picture would indent all of them for nothing. */
    this.toggleAttribute("with-icons", Boolean(this.querySelector("nx-menu-item[icon]")));

    /* A menu that answers a right click is the same menu, put where the
       pointer is and taken away again. It is not carried about and not
       remembered, so it neither drags nor saves. */
    if (this.hasAttribute("context")) {
      this.hidden = true;
      return;
    }

    const name = this.getAttribute("name");
    const saved = recall(name);
    this.style.left = (saved.x ?? Number(this.getAttribute("x"))) + "px";
    this.style.top = (saved.y ?? Number(this.getAttribute("y"))) + "px";

    draggable(this, title, {
      onSettled: () => remember(name, { x: this.offsetLeft, y: this.offsetTop }),
    });
  }

  /**
   * Puts a context menu at the pointer and takes it away on the next click.
   * @param {number} x - Where the pointer was, in the page.
   * @param {number} y
   */
  openAt(x, y) {
    this.hidden = false;
    /* Measured after it is shown, because a hidden element has no size, and
       kept inside the window so a menu near an edge is not half off it. */
    const own = this.getBoundingClientRect();
    this.style.left = Math.min(x, innerWidth - own.width - 2) + "px";
    this.style.top = Math.min(y, innerHeight - own.height - 2) + "px";

    const away = (event) => {
      if (this.contains(event.target)) return;
      this.close();
    };
    this.dismiss = () => {
      removeEventListener("pointerdown", away, true);
      removeEventListener("keydown", escape);
    };
    const escape = (event) => {
      if (event.key === "Escape") this.close();
    };
    addEventListener("pointerdown", away, true);
    addEventListener("keydown", escape);
  }

  /** Takes it away, and stops listening for what would have. */
  close() {
    this.hidden = true;
    this.dismiss?.();
    this.dismiss = null;
  }
}

/**
 * One entry. With `opens` it shows that window, raising it when it is already
 * up, which is what the original did with an entry for a window on screen.
 * @attr opens - The name of an nx-window.
 * @attr key - The letter shown on the right.
 */
class NxMenuItem extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    /* Every entry gets the place, whether it has a picture for it or not, so
       the words all begin at the same column. */
    const art = document.createElement("i");
    art.className = "art mark";
    if (this.hasAttribute("icon")) showArt(art, this.getAttribute("icon"));
    this.prepend(art);
    if (this.hasAttribute("key")) {
      const key = document.createElement("span");
      key.className = "key";
      key.textContent = this.getAttribute("key");
      this.append(key);
    }
    const target = this.getAttribute("opens");
    if (target) {
      this.addEventListener("click", () => {
        if (this.hasAttribute("disabled")) return;
        document.querySelector(`nx-window[name="${target}"]`)?.open(this);
      });
    }
  }
}

/* --- nx-dock ------------------------------------------------------------ */

/**
 * One tile, in the dock or on the floor of the screen.
 * @attr icon - Which picture it carries.
 * @attr opens - The name of an nx-window, if it starts one.
 * @attr idle - Draw the three marks that say the application is not running.
 * @attr spaced - Push it to the foot of the dock.
 *
 * A double click starts it and a single click does nothing, which is what the
 * OpenStep guidelines require and why: a tile is moved by dragging it, and a
 * click that acted would fire whenever somebody began a drag and thought
 * better of it. It also keeps this the same as the File Viewer, where one
 * click chooses and two open.
 */
class NxTile extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const art = document.createElement("i");
    art.className = "art";
    showArt(art, this.getAttribute("icon"));
    this.append(art);

    const target = this.getAttribute("opens");
    if (target) {
      this.addEventListener("dblclick", () => {
        if (this.hasAttribute("disabled")) return;
        document.querySelector(`nx-window[name="${target}"]`)?.open(this);
      });
    }
  }
}

/**
 * Where an application that is not in the dock puts its icon.
 *
 * NeXTSTEP stacked those along the foot of the screen from the left corner
 * rightwards, and took each away when its application went. The tile is the
 * dock's own: `Workspace.app/tile.tiff` is a plain grey square with the icon
 * on it and no lettering, and that is what a tile here already is.
 *
 * An application that has just been started does not simply appear there. Its
 * icon travels from whatever was used to start it, and the tile is in place
 * when it lands.
 */
class NxFloor extends HTMLElement {
  /**
   * Puts the icons there, in the order they were started.
   * @param {Array<object>} running - `{icon, opens}` for each.
   * @param {object} [arriving] - The one that has just started, and where it
   *   is coming from: `{opens, from}` with a DOMRect. Left out, everything is
   *   simply drawn.
   * @returns {Promise} Settled once what arrived has landed.
   */
  async show(running, arriving) {
    const tiles = running.map((application) => this.tile(application));
    const newcomer = arriving && tiles.find(
      (tile) => tile.getAttribute("opens") === arriving.opens);

    if (!newcomer || !arriving.from) {
      this.replaceChildren(...tiles);
      return;
    }

    /* Drawn first and hidden, so the place it is flying to is the place it
       will actually take: the tiles beside it decide that, not this one. */
    this.replaceChildren(...tiles);
    newcomer.style.visibility = "hidden";
    await fly(newcomer.getAttribute("icon"), arriving.from,
              newcomer.getBoundingClientRect());
    newcomer.style.visibility = "";
  }

  /** @returns {HTMLElement} One tile for an application. */
  tile(application) {
    const tile = document.createElement("nx-tile");
    tile.setAttribute("icon", application.icon);
    tile.setAttribute("opens", application.opens);
    return tile;
  }
}

/* --- nx-scroller -------------------------------------------------------- */

/** What differs between the two directions, so that everything else does not
 *  have to know there are two. */
const WAYS = {
  down: {
    steps: ["up", "down"],
    length: "scrollHeight", showing: "clientHeight", along: "scrollTop",
    edge: "top", size: "height", pointer: "clientY", offset: "offsetTop",
    room: "clientHeight",
  },
  across: {
    steps: ["left", "right"],
    length: "scrollWidth", showing: "clientWidth", along: "scrollLeft",
    edge: "left", size: "width", pointer: "clientX", offset: "offsetLeft",
    room: "clientWidth",
  },
};

/**
 * A view with NeXT's scroller on its left: a chequered trough, a knob that
 * takes its size from how much of the content is showing, and both arrows at
 * the far end. With nothing to scroll the whole bar goes empty, which is how
 * an idle terminal looks.
 *
 * @attr bars - Which scrollers this view has: "down", "across", or both.
 *   A view says so because the original's do: the File Viewer's contents have
 *   both, and the band above them, which is a path and only ever grows
 *   sideways, has the one along its foot and nothing down its side. Left out,
 *   it is the vertical one alone, which is what a list wants.
 *
 * A scroller is there whether or not there is anything to scroll. It is part
 * of the view rather than something that appears when it is needed, and an
 * empty trough is what the original shows.
 */
class NxScroller extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    this.view = this.firstElementChild;
    const wanted = (this.getAttribute("bars") || "down").split(/\s+/);
    this.bars = {};
    for (const way of ["down", "across"]) {
      if (wanted.includes(way)) this.bars[way] = this.addBar(way);
    }

    this.view.addEventListener("scroll", () => this.refresh());
    /* Two things change what there is to scroll, and they are seen by two
       different observers: the view being resized, and its content being
       replaced. Content that grows inside an unchanged box moves no edge, so
       the resize observer alone would miss a shelf being redrawn. */
    new ResizeObserver(() => this.refresh()).observe(this.view);
    new MutationObserver(() => this.refresh())
      .observe(this.view, { childList: true, subtree: true, characterData: true });

    this.refresh();
  }

  /**
   * Builds one scroller.
   * @param {string} way - "down" or "across".
   * @returns {object} Its trough, its knob and its arrows.
   */
  addBar(way) {
    const how = WAYS[way];
    const bar = document.createElement("div");
    bar.className = way === "across" ? "bar across" : "bar";
    const trough = document.createElement("div");
    trough.className = "trough";
    const knob = document.createElement("div");
    knob.className = "knob";
    trough.append(knob);

    const arrows = document.createElement("div");
    arrows.className = "arrows";
    for (const step of how.steps) {
      const one = document.createElement("div");
      one.className = "step " + step;
      one.append(document.createElement("i"));
      one.addEventListener("pointerdown", (event) => {
        event.stopPropagation();
        const back = step === "up" || step === "left";
        this.view[how.along] += (back ? -1 : 1) * NxScroller.LINE;
      });
      arrows.append(one);
    }
    bar.append(trough, arrows);
    this.prepend(bar);

    gesture(knob,
      (event, start) => {
        const room = trough[how.room] - knob[how.size === "height" ? "offsetHeight" : "offsetWidth"];
        const at = Math.max(0, Math.min(event[how.pointer] - start.grab, room));
        this.view[how.along] =
          (at / room) * (this.view[how.length] - this.view[how.showing]);
      },
      (event) => ({ grab: event[how.pointer] - knob[how.offset] }));

    return { trough, knob, arrows, how };
  }

  /** Redraws both bars from the view's current state. */
  refresh() {
    for (const bar of Object.values(this.bars)) this.fit(bar);
  }

  /**
   * Draws one bar.
   * @param {object} bar - What addBar returned.
   *
   * A bar with nothing to scroll keeps its trough and loses its knob and its
   * arrows, which is what the original shows: the trough is part of the view
   * rather than a thing that appears when it is needed.
   */
  fit({ trough, knob, arrows, how }) {
    const overflow = this.view[how.length] - this.view[how.showing];
    knob.hidden = overflow <= 0;
    arrows.hidden = overflow <= 0;
    if (overflow <= 0) return;

    const room = trough[how.room];
    const size = Math.max(NxScroller.SMALLEST_KNOB,
                          room * this.view[how.showing] / this.view[how.length]);
    knob.style[how.size] = size + "px";
    knob.style[how.edge] = (this.view[how.along] / overflow) * (room - size) + "px";
  }
}
NxScroller.LINE = 18;            /* how far one press of an arrow moves the view */
NxScroller.SMALLEST_KNOB = 16;   /* below this the knob is no longer a target */

/* --- nx-shelf and nx-thing ---------------------------------------------- */

/** A floor of icons, of which at most one is chosen at a time. */
class NxShelf extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;
    this.addEventListener("click", (event) => {
      const thing = event.target.closest("nx-thing");
      if (!thing || !this.contains(thing)) return;
      if (thing.hasAttribute("disabled")) return;
      this.choose(thing);
    });
  }

  /** @param {HTMLElement} thing - The one to mark, clearing the others. */
  choose(thing) {
    for (const other of this.querySelectorAll("nx-thing")) other.removeAttribute("chosen");
    thing.setAttribute("chosen", "");
  }
}

/**
 * One thing on a shelf: a picture with a name under it.
 * @attr icon - Which picture it carries.
 * @attr label - The name under it.
 * @attr chosen - Draw it selected.
 */
class NxThing extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const slot = document.createElement("span");
    slot.className = "slot art";
    const art = document.createElement("i");
    art.className = "art icon";
    showArt(art, this.getAttribute("icon"));
    slot.append(art);

    const name = document.createElement("span");
    name.className = "name";
    name.textContent = this.getAttribute("label") ?? "";

    this.append(slot, name);
    this.art = art;

    if (this.hasAttribute("value")) this.carry();
    this.draggable = this.canBeUsed;
  }

  /** Watched so that switching a thing off takes its drag handle with it. */
  static get observedAttributes() { return ["disabled"]; }

  attributeChangedCallback() {
    if (this.ready) this.draggable = this.canBeUsed;
  }

  /** @returns {string} What this thing hands over when it is used. */
  get value() { return this.getAttribute("value"); }

  /** @returns {boolean} Whether it hands anything over at all. A thing can be
   *  switched off because using it would do nothing, which is different from
   *  having nothing to give. */
  get canBeUsed() {
    return this.hasAttribute("value") && !this.hasAttribute("disabled");
  }

  /**
   * Makes it liftable, and makes a double click mean the same as carrying it
   * somewhere and letting go.
   *
   * Both raise `nx-choose`, which bubbles, so a page answers in one place
   * however the thing was used.
   */
  carry() {
    this.addEventListener("dragstart", (event) => {
      /* Checked here rather than when this was wired, because a thing is
         switched off and on again whilst the page is up. */
      if (!this.canBeUsed) return event.preventDefault();
      event.dataTransfer.setData("text/plain", this.value);
      event.dataTransfer.effectAllowed = "copy";
      this.setAttribute("lifting", "");
    });

    this.addEventListener("dragend", () => this.removeAttribute("lifting"));

    this.addEventListener("dblclick", () => {
      if (!this.canBeUsed) return;
      this.dispatchEvent(new CustomEvent("nx-choose", {
        bubbles: true, detail: { value: this.value },
      }));
    });
  }

  /** @param {string} icon - Swap the picture without rebuilding the thing. */
  set icon(icon) {
    this.setAttribute("icon", icon);
    if (this.art) showArt(this.art, icon);
  }
}

/* --- nx-ask ------------------------------------------------------------- */

/**
 * The panel that asks before anything changes.
 *
 * NeXTSTEP put an attention panel in the middle of the screen over a dimmed
 * desk, with the icon of whatever is about to happen, a sentence saying what
 * it is, and the safe answer on the left. This is that, and it is a component
 * rather than markup in the page because more than one thing needs to ask:
 * stopping the emulator does, and changing the machine will.
 *
 * It answers with a promise rather than a callback, so the caller reads as one
 * sequence: ask, then act on the answer.
 */
class NxAsk extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;
    this.className = "scrim";

    this.innerHTML = `
      <div class="panel">
        <div class="titlebar"><div class="title"></div></div>
        <div class="pane">
          <div class="panel-body">
            <i class="art icon"></i>
            <div class="words">
              <div class="lines"></div>
              <input class="entry" type="text" spellcheck="false" hidden>
            </div>
          </div>
          <div class="buttons" style="padding-right:0">
            <button data-answer="no"></button>
            <button data-answer="yes" class="default"></button>
          </div>
        </div>
      </div>`;

    this.settle = null;
    for (const button of this.querySelectorAll("button")) {
      button.addEventListener("click", () => this.close(button.dataset.answer === "yes"));
    }

    /* Escape is the safe answer, which is the one a panel like this must have:
       somebody who wants out of a question should not have to aim at a button. */
    this.keys = (event) => {
      if (event.key === "Escape") this.close(false);
      const entry = this.querySelector(".entry");
      if (event.key === "Enter" && !entry.hidden) this.close(true);
    };
  }

  /**
   * Puts the question and waits for an answer.
   * @param {object} question
   * @param {string} question.title - The panel's own title bar.
   * @param {string[]} question.text - One paragraph per entry.
   * @param {string} [question.icon] - Which picture, by the name showArt knows.
   * @param {string} question.confirm - The wording on the acting button. The
   *   kit holds no words of its own, in any language, so both buttons are
   *   named by whoever asks.
   * @param {string} question.cancel - The wording on the safe one.
   * @param {boolean} [question.field] - Show a line to type into.
   * @returns {Promise<boolean>} True where the acting button was pressed.
   */
  ask({ title, text, icon, confirm, cancel, field = false }) {
    this.querySelector(".title").textContent = title;
    this.querySelector(".lines").replaceChildren(
      ...text.map((line) => {
        const paragraph = document.createElement("p");
        paragraph.textContent = line;
        return paragraph;
      }));
    if (icon) showArt(this.querySelector(".icon"), icon);
    this.querySelector('[data-answer="yes"]').textContent = confirm;
    this.querySelector('[data-answer="no"]').textContent = cancel;

    const entry = this.querySelector(".entry");
    entry.hidden = !field;
    entry.value = "";

    this.toggleAttribute("data-open", true);
    addEventListener("keydown", this.keys);
    (field ? entry : this.querySelector('[data-answer="no"]')).focus();

    return new Promise((settle) => { this.settle = settle; });
  }

  /**
   * Puts a question that needs something typed.
   * @param {object} question - As ask, and the field is shown.
   * @returns {Promise<string|null>} What was typed, or null where the panel was
   *   dismissed. Empty counts as dismissed, because a blank answer is not one.
   */
  async askFor(question) {
    const answered = await this.ask({ ...question, field: true });
    if (!answered) return null;
    const typed = this.querySelector(".entry").value.trim();
    return typed || null;
  }

  /**
   * Closes the panel and settles whoever was waiting.
   * @param {boolean} answer
   */
  close(answer) {
    this.toggleAttribute("data-open", false);
    removeEventListener("keydown", this.keys);
    this.settle?.(answer);
    this.settle = null;
  }
}

/* --- nx-viewer ---------------------------------------------------------- */

/**
 * NeXTSTEP's File Viewer, which is four bands stacked in one window.
 *
 * The shelf along the top keeps whatever is dropped on it and has nothing to
 * do with where you are. Under it one line of status about the whole. Then the
 * path, as a row of icons with an arrow between each pair. Then what the last
 * step of that path holds, in a scroller.
 *
 * It knows nothing about what it is showing. The page hands it a path and a
 * list of contents and listens for what was chosen, so the same component
 * serves machines, a shared directory, or anything else that is a place with
 * things in it.
 *
 * @attr status - The line under the shelf, where the page has nothing more
 *   particular to say.
 * @fires nx-path - A step of the path was chosen, carrying its index in
 *   `detail.index` and its value in `detail.value`.
 * @fires nx-visit - Something on the shelf was clicked once, carrying its
 *   value. One click there is an act rather than a selection.
 * @fires nx-choose - Something in the contents or on the shelf was chosen,
 *   from nx-thing, carrying its value.
 */
class NxViewer extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    this.keep = document.createElement("nx-shelf");
    this.keep.className = "keep";

    /* One click on the shelf is an act, which is the one place in this viewer
       where that is true: NeXT's guidelines say that clicking a folder there
       changes what the viewer shows, and that a drag must not do the same,
       which is why the shelf is the example they use for it. */
    this.keep.addEventListener("click", (event) => {
      const thing = event.target.closest("nx-thing");
      if (!thing || !this.keep.contains(thing)) return;
      /* Raised on the thing rather than on the viewer, so that whoever
         answers knows which icon was clicked and not merely that one was.
         An icon that travels has to start where it is. */
      thing.dispatchEvent(new CustomEvent("nx-visit", {
        bubbles: true,
        detail: { value: thing.getAttribute("value") },
      }));
    });
    this.keep.addEventListener("dragover", (event) => {
      event.preventDefault();
      event.dataTransfer.dropEffect = "copy";
      this.keep.setAttribute("droppable", "");
    });
    this.keep.addEventListener("dragleave", (event) => {
      if (!this.keep.contains(event.relatedTarget)) this.keep.removeAttribute("droppable");
    });
    this.keep.addEventListener("drop", (event) => {
      event.preventDefault();
      this.keep.removeAttribute("droppable");
      this.dispatchEvent(new CustomEvent("nx-keep", {
        bubbles: true,
        detail: { value: event.dataTransfer.getData("text/plain") },
      }));
    });

    this.status = document.createElement("p");
    this.status.className = "status";
    this.status.textContent = this.getAttribute("status") ?? "";

    this.path = document.createElement("div");
    this.path.className = "path";
    this.path.addEventListener("click", (event) => {
      const thing = event.target.closest("nx-thing");
      if (!thing || !this.path.contains(thing)) return;
      this.dispatchEvent(new CustomEvent("nx-path", {
        bubbles: true,
        detail: { index: Number(thing.dataset.step), value: thing.getAttribute("value") },
      }));
    });

    /* The path is a browser in the original and scrolls sideways as it grows,
       with its trough under it whether there is anything to scroll or not. */
    const way = document.createElement("nx-scroller");
    way.setAttribute("bars", "across");
    way.className = "way";
    way.append(this.path);

    this.contents = document.createElement("nx-shelf");
    this.contents.className = "contents";
    const scroller = document.createElement("nx-scroller");
    scroller.setAttribute("bars", "down across");
    scroller.append(this.contents);

    this.append(this.keep, this.status, way, scroller);
  }

  /**
   * Puts a place and its contents in the window.
   * @param {object} view
   * @param {Array<object>} view.path - The way here, outermost first. Each is
   *   `{label, icon, value}`.
   * @param {Array<object>} view.contents - What the last step holds. Each is
   *   `{label, icon, value}`, and `folder` marks one that has more inside.
   * @param {Array<object>} [view.keeps] - What lies on the shelf, the same
   *   shape. Left out, the shelf is not touched.
   * @param {string} [view.status] - The line under the shelf.
   */
  show({ path = [], contents = [], keeps, status }) {
    if (status !== undefined) this.status.textContent = status;
    if (keeps !== undefined) {
      this.keep.replaceChildren(...keeps.map((entry) => this.thing(entry)));
    }

    this.path.replaceChildren(...path.flatMap((step, index) => {
      const thing = this.thing(step);
      thing.dataset.step = String(index);
      /* The last step is where you are, and the shape that says so is the one
         a chosen thing already wears. */
      if (index === path.length - 1) thing.setAttribute("chosen", "");
      if (index === 0) return [thing];
      return [this.arrow(), thing];
    }));

    this.contents.replaceChildren(...contents.map((entry) => {
      const thing = this.thing(entry);
      if (entry.folder) thing.setAttribute("folder", "");
      return thing;
    }));
  }

  /**
   * @param {object} entry - `{label, icon, value}`.
   * @returns {HTMLElement} The icon with its name, ready to be appended.
   */
  thing(entry) {
    const thing = document.createElement("nx-thing");
    thing.setAttribute("icon", entry.icon ?? "");
    thing.setAttribute("label", entry.label ?? "");
    if (entry.value !== undefined) thing.setAttribute("value", entry.value);
    return thing;
  }

  /** @returns {HTMLElement} The mark between two steps of the path. */
  arrow() {
    const arrow = document.createElement("i");
    arrow.className = "step-arrow";
    return arrow;
  }
}

for (const [tag, type] of [
  ["nx-window", NxWindow],
  ["nx-menu", NxMenu],
  ["nx-menu-item", NxMenuItem],
  ["nx-tile", NxTile],
  ["nx-floor", NxFloor],
  ["nx-scroller", NxScroller],
  ["nx-shelf", NxShelf],
  ["nx-thing", NxThing],
  ["nx-ask", NxAsk],
  ["nx-viewer", NxViewer],
]) {
  customElements.define(tag, type);
}

/* After the definitions, because every window has to exist and know
   whether it is open before one of them can be picked out as the
   front one. */
restoreFront();
