/* The NeXTSTEP kit: everything the interface is built from.
 *
 * Generated by design/build.py from design/kit/. Do not edit by hand.
 *
 * Each part is one source in design/kit/, holding its element and its
 * styles together:
 *
 *   base                   the tokens, the reset and the two edges
 *   desk                   what the desk remembers, and the gestures
 *   nx-window              a frame that drags, resizes, closes and remembers
 *   nx-menu, nx-menu-item  the menu, and the entries that open windows
 *   nx-tile                the strip of tiles down the right edge
 *   nx-scroller            a view with NeXT's scroller on its left
 *   nx-shelf, nx-thing     a floor of icons, one of which may be chosen
 *   nx-ask                 the panel that asks before a change
 *   nx-viewer              the File Viewer, as four bands in one window
 *   panel                  nx-portrait, nx-row and nx-field, for an info panel
 *   terminal               a text view, black on white
 *
 * They use the light DOM rather than a shadow root, so the stylesheet
 * reaches them and the design tokens carry through.
 */

const SVG_NS = "http://www.w3.org/2000/svg";
const STORE = "nextstep-workspace:v4";

/* --- what the desk remembers -------------------------------------------- */

/** @returns {object} Everything saved about the desk, or an empty record. */
function readState() {
  try { return JSON.parse(localStorage.getItem(STORE)) ?? {}; }
  catch { return {}; }
}

/**
 * Writes one element's state, leaving every other one untouched.
 * @param {string} name - What the element calls itself.
 * @param {object} state - The keys to merge in.
 */
function remember(name, state) {
  const all = readState();
  all[name] = { ...(all[name] ?? {}), ...state };
  localStorage.setItem(STORE, JSON.stringify(all));
}

/** @param {string} name @returns {object} That element's saved state. */
function recall(name) {
  return readState()[name] ?? {};
}

/**
 * Points an element at one of the pictures build.py baked into the stylesheet.
 * @param {HTMLElement} el
 * @param {string} name - The picture's name, which is its file's stem.
 */
function showArt(el, name) {
  el.style.backgroundImage = "var(--" + name + ")";
}

/**
 * Runs a pointer gesture and reports the result when it ends.
 * @param {HTMLElement} handle - Where the gesture starts.
 * @param {(event: PointerEvent, start: object) => void} onMove
 * @param {(event: PointerEvent) => object} onStart - Whatever the mover needs
 *   to know about the moment the gesture began.
 * @param {(start: object) => void} [onEnd] - Given what onStart returned,
 *   which by then carries whatever the moves wrote into it.
 */
function gesture(handle, onMove, onStart, onEnd) {
  handle.addEventListener("pointerdown", (event) => {
    event.stopPropagation();
    /* Without this the browser starts its own text selection under the
       pointer, and dragging a window paints half the desk blue. */
    event.preventDefault();
    handle.setPointerCapture(event.pointerId);
    const start = onStart(event);

    /* A pointer reports faster than the screen redraws, so the moves are
       coalesced into one update per frame. Everything beyond the last one in
       a frame is work whose result is painted over before anybody sees it. */
    let latest = null;
    let frame = 0;

    const apply = () => {
      frame = 0;
      onMove(latest, start);
    };

    const move = (moveEvent) => {
      latest = moveEvent;
      if (!frame) frame = requestAnimationFrame(apply);
    };

    const finish = () => {
      handle.removeEventListener("pointermove", move);
      /* The last position has to land before anything saves it, so a frame
         still owed is run now rather than cancelled. */
      if (frame) {
        cancelAnimationFrame(frame);
        apply();
      }
      onEnd?.(start);
    };

    handle.addEventListener("pointermove", move);
    handle.addEventListener("pointerup", finish, { once: true });
    handle.addEventListener("pointercancel", finish, { once: true });
  });
}

/**
 * Moves an element by its handle, and settles it where it was let go.
 *
 * Whilst the gesture runs the element is moved with a transform, which the
 * compositor can do without laying the page out again. Its left and top are
 * written once, at the end, so everything that reads them afterwards sees a
 * plain position and knows nothing about how it got there.
 *
 * @param {HTMLElement} element - What moves.
 * @param {HTMLElement} handle - What is grabbed.
 * @param {object} hooks
 * @param {() => void} [hooks.onGrab] - Called as the gesture begins.
 * @param {() => void} [hooks.onSettled] - Called once the position is written.
 */
function draggable(element, handle, { onGrab, onSettled } = {}) {
  gesture(handle,
    (event, start) => {
      /* Never past the top or left edge, and never wholly behind the dock. */
      start.left = Math.max(0, Math.min(event.clientX - start.grabX, innerWidth - 90));
      start.top = Math.max(0, Math.min(event.clientY - start.grabY, innerHeight - 24));
      element.style.transform =
        `translate(${start.left - start.fromLeft}px, ${start.top - start.fromTop}px)`;
    },
    (event) => {
      onGrab?.();
      const fromLeft = element.offsetLeft;
      const fromTop = element.offsetTop;
      return {
        grabX: event.clientX - fromLeft, grabY: event.clientY - fromTop,
        fromLeft, fromTop, left: fromLeft, top: fromTop,
      };
    },
    (start) => {
      element.style.transform = "";
      element.style.left = start.left + "px";
      element.style.top = start.top + "px";
      onSettled?.();
    });
}

/* --- the desk does not hold text -----------------------------------------

   user-select says a selection may not begin inside an element. It does not
   stop a browser that begins one anyway, and a drag across a shelf then leaves
   every label it passed highlighted in the browser's own blue.

   Refused here rather than in a stylesheet, because this holds whatever the
   browser makes of the property. A terminal is the exception: reading
   something out of it is the point of having one. */
addEventListener("selectstart", (event) => {
  if (!event.target.closest?.(".terminal")) event.preventDefault();
});

/* --- the letters beside the menu entries ---------------------------------

   NeXTSTEP drew those for Command key shortcuts. Command and Control both
   belong to the browser here, so the letter acts on its own, and three
   conditions keep that from being a nuisance: nothing held down, nothing being
   typed into, and no panel up, because a panel has a keyboard of its own and
   two answers to give with it.

   A context menu is left out. Its entries act on whatever was right clicked,
   and a key press has nothing under the pointer. */
addEventListener("keydown", (event) => {
  if (event.metaKey || event.ctrlKey || event.altKey) return;
  if (document.querySelector("nx-ask[data-open]")) return;

  const focused = document.activeElement;
  if (focused?.matches?.("input, textarea, select") || focused?.isContentEditable) return;

  const pressed = event.key.toLowerCase();
  const item = [...document.querySelectorAll("nx-menu:not([context]) nx-menu-item[key]")]
    .find((entry) => entry.getAttribute("key").toLowerCase() === pressed);
  if (!item || item.hasAttribute("disabled")) return;

  event.preventDefault();
  item.click();
});

/**
 * Puts the front window back in front and every other one behind it.
 *
 * This runs over all the windows rather than inside any one of them, because
 * being in front is a statement about all of them together: a window can only
 * make itself active by making the others inactive, and at a load none of them
 * has done that yet. Without it every title bar is drawn active, which is a
 * desk NeXTSTEP never showed.
 *
 * Without a remembered name the last open window in the markup takes it, which
 * is the one a reader would call the frontmost.
 */
function restoreFront() {
  const windows = [...document.querySelectorAll("nx-window")];
  for (const window_ of windows) window_.setAttribute("inactive", "");
  const remembered = recall("desk").front;
  const open = windows.filter((window_) => !window_.hidden);
  const front = open.find((window_) => window_.name === remembered) ?? open.at(-1);
  front?.raise();
}

/* --- nx-window ---------------------------------------------------------- */

/**
 * A window: title bar, close button, optional resize bar, and a memory.
 *
 * It writes its position, its size and whether it is open under its name, so
 * the desk comes back the way it was left. A window marked `fixed` has no
 * resize bar, one marked `flush` lets its content run to the frame, and one
 * marked `drop` accepts things dragged onto it.
 *
 * @attr name   - What it is called in storage and to the menu. Required.
 * @attr title  - The text in the bar.
 * @attr x y w h - Where it starts, before anything was remembered.
 * @attr min-w min-h - The floor its content needs.
 */
class NxWindow extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const content = [...this.childNodes];
    this.replaceChildren();

    this.bar = this.build("div", "titlebar");
    this.bar.append(this.build("i", "art wbtn mini"));
    const title = this.build("div", "title");
    title.textContent = this.getAttribute("title") ?? "";
    this.removeAttribute("title");         /* or the browser shows a tooltip */
    const close = this.build("i", "art wbtn close");
    this.bar.append(title, close);

    this.pane = this.build("div", "pane");
    this.pane.append(...content);
    this.append(this.bar, this.pane);

    if (!this.hasAttribute("fixed")) this.addResizer();
    if (this.hasAttribute("drop")) this.acceptDrops();
    this.place();
    this.wire(close);
  }

  /**
   * Puts a different name in the title bar.
   * @param {string} text - What the window is about now.
   *
   * For a window that says something about whatever was chosen, where the
   * name is the difference between two of them.
   */
  rename(text) {
    const title = this.bar?.querySelector(".title");
    if (title) title.textContent = text;
  }

  /** @returns {HTMLElement} A child element, appended nowhere yet. */
  build(tag, className) {
    const el = document.createElement(tag);
    el.className = className;
    return el;
  }

  /** Puts the window where it was left, or where its attributes say. */
  place() {
    const saved = recall(this.name);
    const number = (key, attribute) => saved[key] ?? Number(this.getAttribute(attribute));
    /* A window nobody can resize has no size of its own to remember, so its
       markup decides. Otherwise a size saved before it was fixed, or before
       its contents changed, would outlive both. */
    const fixed = this.hasAttribute("fixed");
    const size = fixed
      ? (_key, attribute) => Number(this.getAttribute(attribute))
      : number;

    this.style.left = Math.min(number("x", "x"), Math.max(0, innerWidth - 90)) + "px";
    this.style.top = Math.min(number("y", "y"), Math.max(0, innerHeight - 40)) + "px";

    /* Before the size, because the floor is read off these and a size saved
       when the window held something else has to be held to what it holds
       now. */
    for (const [attribute, property] of [["min-w", "--win-min-w"], ["min-h", "--win-min-h"]]) {
      if (this.hasAttribute(attribute)) {
        this.style.setProperty(property, this.getAttribute(attribute) + "px");
      }
    }
    const floor = this.floor;

    this.style.width = Math.max(size("w", "w"), floor.width) + "px";

    /* A fixed window is as tall as what is in it, unless its markup says
       otherwise. A height written by hand is a number that stops being right
       the moment a row is added, and both windows here had drifted that way.
       Width stays a decision, because a column of readings has no natural
       one. */
    this.style.height = fixed && !this.hasAttribute("h")
      ? "auto"
      : Math.max(size("h", "h"), floor.height) + "px";
    /* A window is open unless it says otherwise, and what was remembered
       beats what the markup starts it at. */
    this.hidden = !(saved.open ?? !this.hasAttribute("closed"));
  }

  /** @returns {string} The name it is known by. */
  get name() { return this.getAttribute("name"); }

  /** The floor this window's content needs, read off the element itself. */
  get floor() {
    const style = getComputedStyle(this);
    return {
      width: parseInt(style.getPropertyValue("--win-min-w"), 10),
      height: parseInt(style.getPropertyValue("--win-min-h"), 10),
    };
  }

  /**
   * Saves whether it is open, and where and how big it is.
   *
   * A hidden element measures zero on every side, so a closed window keeps the
   * geometry it had rather than writing that over with nothing. Otherwise it
   * would come back in the corner at no size at all.
   */
  save() {
    const state = { open: !this.hidden };
    if (!this.hidden) {
      Object.assign(state, {
        x: this.offsetLeft, y: this.offsetTop,
        w: this.offsetWidth, h: this.offsetHeight,
      });
    }
    remember(this.name, state);
  }

  /**
   * Brings it forward and pushes every other window back. Which window is in
   * front is part of what the desk remembers, because exactly one is active at
   * a time and a reload that made them all active would be a desk nobody has
   * ever seen.
   */
  raise() {
    if (!this.hasAttribute("inactive") && this.style.zIndex) return;
    let highest = 10;
    for (const other of document.querySelectorAll("nx-window")) {
      highest = Math.max(highest, Number(other.style.zIndex) || 10);
      other.setAttribute("inactive", "");
    }
    this.style.zIndex = highest + 1;
    this.removeAttribute("inactive");
    remember("desk", { front: this.name });
  }

  /** Shows it, in front. */
  open() {
    this.hidden = false;
    this.raise();
    this.save();
    /* So whatever fills this window can fill it now rather than at the next
       poll, which is up to five seconds of dashes. */
    this.dispatchEvent(new CustomEvent("nx-open", { bubbles: true }));
  }

  /** Hides it, keeping its geometry for the next time. */
  close() {
    this.hidden = true;
    this.save();
  }

  /**
   * Takes what is dropped on it, and says so whilst something is over it.
   *
   * Raises the same `nx-choose` a double click does, because carrying a thing
   * here and double clicking it mean the same thing to whoever answers.
   */
  acceptDrops() {
    this.addEventListener("dragover", (event) => {
      event.preventDefault();
      event.dataTransfer.dropEffect = "copy";
      this.setAttribute("droppable", "");
    });

    /* Moving onto a child fires dragleave on the parent, so only a pointer
       that has actually left the window counts. */
    this.addEventListener("dragleave", (event) => {
      if (!this.contains(event.relatedTarget)) this.removeAttribute("droppable");
    });

    this.addEventListener("drop", (event) => {
      event.preventDefault();
      this.removeAttribute("droppable");
      this.dispatchEvent(new CustomEvent("nx-choose", {
        bubbles: true,
        detail: { value: event.dataTransfer.getData("text/plain") },
      }));
    });
  }

  /** The bar along the foot: a middle that takes the height and two ends that
   *  take the corner with it. */
  addResizer() {
    const bar = this.build("div", "resizer");
    const left = this.build("div", "end");
    const right = this.build("div", "end");
    left.dataset.corner = "left";
    right.dataset.corner = "right";
    bar.append(left, this.build("div", "middle"), right);
    this.append(bar);

    for (const handle of bar.children) {
      const corner = handle.dataset.corner;
      gesture(handle,
        (event, start) => {
          const floor = this.floor;
          this.style.height = Math.max(floor.height, start.height + event.clientY) + "px";
          if (corner === "right") {
            this.style.width = Math.max(floor.width, start.width + event.clientX) + "px";
          } else if (corner === "left") {
            /* Dragging the left end moves that edge and holds the right one
               still, so the two have to change together. */
            const left = Math.min(event.clientX - start.grabX, start.right - floor.width);
            this.style.left = left + "px";
            this.style.width = (start.right - left) + "px";
          }
        },
        (event) => {
          this.raise();
          return {
            width: this.offsetWidth - event.clientX,
            height: this.offsetHeight - event.clientY,
            grabX: event.clientX - this.offsetLeft,
            right: this.offsetLeft + this.offsetWidth,
          };
        },
        () => this.save());
    }
  }

  /** Dragging by the bar, closing by the button, raising by a click anywhere. */
  wire(close) {
    draggable(this, this.bar, {
      onGrab: () => this.raise(),
      onSettled: () => this.save(),
    });

    close.addEventListener("click", (event) => {
      event.stopPropagation();
      this.close();
    });
    /* The bar's own gesture would otherwise start a drag from the button, and
       the window would follow the pointer as it closed. */
    close.addEventListener("pointerdown", (event) => event.stopPropagation());

    this.addEventListener("pointerdown", () => this.raise());
  }
}

/* --- nx-menu ------------------------------------------------------------ */

/**
 * The menu: a title that drags the whole thing, and entries beneath it.
 * @attr name - What it is called in storage.
 * @attr title - The text in its black bar.
 * @attr x y - Where it starts.
 */
class NxMenu extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const title = document.createElement("div");
    title.className = "title";
    title.textContent = this.getAttribute("title") ?? "";
    this.removeAttribute("title");
    this.prepend(title);

    /* Whether to keep a column for pictures is the menu's decision and not
       each entry's: the words line up when every entry holds the place, and a
       menu where nothing has a picture would indent all of them for nothing. */
    this.toggleAttribute("with-icons", Boolean(this.querySelector("nx-menu-item[icon]")));

    /* A menu that answers a right click is the same menu, put where the
       pointer is and taken away again. It is not carried about and not
       remembered, so it neither drags nor saves. */
    if (this.hasAttribute("context")) {
      this.hidden = true;
      return;
    }

    const name = this.getAttribute("name");
    const saved = recall(name);
    this.style.left = (saved.x ?? Number(this.getAttribute("x"))) + "px";
    this.style.top = (saved.y ?? Number(this.getAttribute("y"))) + "px";

    draggable(this, title, {
      onSettled: () => remember(name, { x: this.offsetLeft, y: this.offsetTop }),
    });
  }

  /**
   * Puts a context menu at the pointer and takes it away on the next click.
   * @param {number} x - Where the pointer was, in the page.
   * @param {number} y
   */
  openAt(x, y) {
    this.hidden = false;
    /* Measured after it is shown, because a hidden element has no size, and
       kept inside the window so a menu near an edge is not half off it. */
    const own = this.getBoundingClientRect();
    this.style.left = Math.min(x, innerWidth - own.width - 2) + "px";
    this.style.top = Math.min(y, innerHeight - own.height - 2) + "px";

    const away = (event) => {
      if (this.contains(event.target)) return;
      this.close();
    };
    this.dismiss = () => {
      removeEventListener("pointerdown", away, true);
      removeEventListener("keydown", escape);
    };
    const escape = (event) => {
      if (event.key === "Escape") this.close();
    };
    addEventListener("pointerdown", away, true);
    addEventListener("keydown", escape);
  }

  /** Takes it away, and stops listening for what would have. */
  close() {
    this.hidden = true;
    this.dismiss?.();
    this.dismiss = null;
  }
}

/**
 * One entry. With `opens` it shows that window, raising it when it is already
 * up, which is what the original did with an entry for a window on screen.
 * @attr opens - The name of an nx-window.
 * @attr key - The letter shown on the right.
 */
class NxMenuItem extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    /* Every entry gets the place, whether it has a picture for it or not, so
       the words all begin at the same column. */
    const art = document.createElement("i");
    art.className = "art mark";
    if (this.hasAttribute("icon")) showArt(art, this.getAttribute("icon"));
    this.prepend(art);
    if (this.hasAttribute("key")) {
      const key = document.createElement("span");
      key.className = "key";
      key.textContent = this.getAttribute("key");
      this.append(key);
    }
    const target = this.getAttribute("opens");
    if (target) {
      this.addEventListener("click", () => {
        if (this.hasAttribute("disabled")) return;
        document.querySelector(`nx-window[name="${target}"]`)?.open();
      });
    }
  }
}

/* --- nx-dock ------------------------------------------------------------ */

/**
 * One dock tile.
 * @attr icon - Which picture it carries.
 * @attr opens - The name of an nx-window, if clicking it should show one.
 * @attr idle - Draw the three marks that said the application was not started.
 * @attr spaced - Push it to the foot of the dock.
 */
class NxTile extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const art = document.createElement("i");
    art.className = "art";
    showArt(art, this.getAttribute("icon"));
    this.append(art);

    const target = this.getAttribute("opens");
    if (target) {
      this.addEventListener("click", () => {
        if (this.hasAttribute("disabled")) return;
        document.querySelector(`nx-window[name="${target}"]`)?.open();
      });
    }
  }
}

/* --- nx-scroller -------------------------------------------------------- */

/**
 * A view with NeXT's scroller on its left: a chequered trough, a knob that
 * takes its size from how much of the content is showing, and both arrows at
 * the foot. With nothing to scroll the whole bar goes empty, which is how an
 * idle terminal looks.
 */
class NxScroller extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    this.view = this.firstElementChild;
    const bar = document.createElement("div");
    bar.className = "bar";
    this.trough = document.createElement("div");
    this.trough.className = "trough";
    this.knob = document.createElement("div");
    this.knob.className = "knob";
    this.trough.append(this.knob);
    this.arrows = document.createElement("div");
    this.arrows.className = "arrows";
    for (const direction of ["up", "down"]) {
      const step = document.createElement("div");
      step.className = "step " + direction;
      step.append(document.createElement("i"));
      step.addEventListener("pointerdown", (event) => {
        event.stopPropagation();
        this.view.scrollTop += (direction === "up" ? -1 : 1) * NxScroller.LINE;
      });
      this.arrows.append(step);
    }
    bar.append(this.trough, this.arrows);
    this.prepend(bar);

    this.view.addEventListener("scroll", () => this.refresh());
    /* Two things change what there is to scroll, and they are seen by two
       different observers: the view being resized, and its content being
       replaced. Content that grows inside an unchanged box moves no edge, so
       the resize observer alone would miss a shelf being redrawn. */
    new ResizeObserver(() => this.refresh()).observe(this.view);
    new MutationObserver(() => this.refresh())
      .observe(this.view, { childList: true, subtree: true, characterData: true });

    gesture(this.knob,
      (event, start) => {
        const room = this.trough.clientHeight - this.knob.offsetHeight;
        const top = Math.max(0, Math.min(event.clientY - start.grab, room));
        this.view.scrollTop = (top / room) * (this.view.scrollHeight - this.view.clientHeight);
      },
      (event) => ({ grab: event.clientY - this.knob.offsetTop }));

    this.refresh();
  }

  /** Redraws the bar from the view's current state. */
  refresh() {
    const overflow = this.view.scrollHeight - this.view.clientHeight;
    this.knob.hidden = overflow <= 0;
    this.arrows.hidden = overflow <= 0;
    if (overflow <= 0) return;

    const room = this.trough.clientHeight;
    const height = Math.max(NxScroller.SMALLEST_KNOB,
                            room * this.view.clientHeight / this.view.scrollHeight);
    this.knob.style.height = height + "px";
    this.knob.style.top = (this.view.scrollTop / overflow) * (room - height) + "px";
  }
}
NxScroller.LINE = 18;            /* how far one press of an arrow moves the view */
NxScroller.SMALLEST_KNOB = 16;   /* below this the knob is no longer a target */

/* --- nx-shelf and nx-thing ---------------------------------------------- */

/** A floor of icons, of which at most one is chosen at a time. */
class NxShelf extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;
    this.addEventListener("click", (event) => {
      const thing = event.target.closest("nx-thing");
      if (!thing || !this.contains(thing)) return;
      if (thing.hasAttribute("disabled")) return;
      this.choose(thing);
    });
  }

  /** @param {HTMLElement} thing - The one to mark, clearing the others. */
  choose(thing) {
    for (const other of this.querySelectorAll("nx-thing")) other.removeAttribute("chosen");
    thing.setAttribute("chosen", "");
  }
}

/**
 * One thing on a shelf: a picture with a name under it.
 * @attr icon - Which picture it carries.
 * @attr label - The name under it.
 * @attr chosen - Draw it selected.
 */
class NxThing extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    const slot = document.createElement("span");
    slot.className = "slot art";
    const art = document.createElement("i");
    art.className = "art icon";
    showArt(art, this.getAttribute("icon"));
    slot.append(art);

    const name = document.createElement("span");
    name.className = "name";
    name.textContent = this.getAttribute("label") ?? "";

    this.append(slot, name);
    this.art = art;

    if (this.hasAttribute("value")) this.carry();
    this.draggable = this.canBeUsed;
  }

  /** Watched so that switching a thing off takes its drag handle with it. */
  static get observedAttributes() { return ["disabled"]; }

  attributeChangedCallback() {
    if (this.ready) this.draggable = this.canBeUsed;
  }

  /** @returns {string} What this thing hands over when it is used. */
  get value() { return this.getAttribute("value"); }

  /** @returns {boolean} Whether it hands anything over at all. A thing can be
   *  switched off because using it would do nothing, which is different from
   *  having nothing to give. */
  get canBeUsed() {
    return this.hasAttribute("value") && !this.hasAttribute("disabled");
  }

  /**
   * Makes it liftable, and makes a double click mean the same as carrying it
   * somewhere and letting go.
   *
   * Both raise `nx-choose`, which bubbles, so a page answers in one place
   * however the thing was used.
   */
  carry() {
    this.addEventListener("dragstart", (event) => {
      /* Checked here rather than when this was wired, because a thing is
         switched off and on again whilst the page is up. */
      if (!this.canBeUsed) return event.preventDefault();
      event.dataTransfer.setData("text/plain", this.value);
      event.dataTransfer.effectAllowed = "copy";
      this.setAttribute("lifting", "");
    });

    this.addEventListener("dragend", () => this.removeAttribute("lifting"));

    this.addEventListener("dblclick", () => {
      if (!this.canBeUsed) return;
      this.dispatchEvent(new CustomEvent("nx-choose", {
        bubbles: true, detail: { value: this.value },
      }));
    });
  }

  /** @param {string} icon - Swap the picture without rebuilding the thing. */
  set icon(icon) {
    this.setAttribute("icon", icon);
    if (this.art) showArt(this.art, icon);
  }
}

/* --- nx-ask ------------------------------------------------------------- */

/**
 * The panel that asks before anything changes.
 *
 * NeXTSTEP put an attention panel in the middle of the screen over a dimmed
 * desk, with the icon of whatever is about to happen, a sentence saying what
 * it is, and the safe answer on the left. This is that, and it is a component
 * rather than markup in the page because more than one thing needs to ask:
 * stopping the emulator does, and changing the machine will.
 *
 * It answers with a promise rather than a callback, so the caller reads as one
 * sequence: ask, then act on the answer.
 */
class NxAsk extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;
    this.className = "scrim";

    this.innerHTML = `
      <div class="panel">
        <div class="titlebar"><div class="title"></div></div>
        <div class="pane">
          <div class="panel-body">
            <i class="art icon"></i>
            <div class="words">
              <div class="lines"></div>
              <input class="entry" type="text" spellcheck="false" hidden>
            </div>
          </div>
          <div class="buttons" style="padding-right:0">
            <button data-answer="no"></button>
            <button data-answer="yes" class="default"></button>
          </div>
        </div>
      </div>`;

    this.settle = null;
    for (const button of this.querySelectorAll("button")) {
      button.addEventListener("click", () => this.close(button.dataset.answer === "yes"));
    }

    /* Escape is the safe answer, which is the one a panel like this must have:
       somebody who wants out of a question should not have to aim at a button. */
    this.keys = (event) => {
      if (event.key === "Escape") this.close(false);
      const entry = this.querySelector(".entry");
      if (event.key === "Enter" && !entry.hidden) this.close(true);
    };
  }

  /**
   * Puts the question and waits for an answer.
   * @param {object} question
   * @param {string} question.title - The panel's own title bar.
   * @param {string[]} question.text - One paragraph per entry.
   * @param {string} [question.icon] - Which picture, by the name showArt knows.
   * @param {string} question.confirm - The wording on the acting button. The
   *   kit holds no words of its own, in any language, so both buttons are
   *   named by whoever asks.
   * @param {string} question.cancel - The wording on the safe one.
   * @param {boolean} [question.field] - Show a line to type into.
   * @returns {Promise<boolean>} True where the acting button was pressed.
   */
  ask({ title, text, icon, confirm, cancel, field = false }) {
    this.querySelector(".title").textContent = title;
    this.querySelector(".lines").replaceChildren(
      ...text.map((line) => {
        const paragraph = document.createElement("p");
        paragraph.textContent = line;
        return paragraph;
      }));
    if (icon) showArt(this.querySelector(".icon"), icon);
    this.querySelector('[data-answer="yes"]').textContent = confirm;
    this.querySelector('[data-answer="no"]').textContent = cancel;

    const entry = this.querySelector(".entry");
    entry.hidden = !field;
    entry.value = "";

    this.toggleAttribute("data-open", true);
    addEventListener("keydown", this.keys);
    (field ? entry : this.querySelector('[data-answer="no"]')).focus();

    return new Promise((settle) => { this.settle = settle; });
  }

  /**
   * Puts a question that needs something typed.
   * @param {object} question - As ask, and the field is shown.
   * @returns {Promise<string|null>} What was typed, or null where the panel was
   *   dismissed. Empty counts as dismissed, because a blank answer is not one.
   */
  async askFor(question) {
    const answered = await this.ask({ ...question, field: true });
    if (!answered) return null;
    const typed = this.querySelector(".entry").value.trim();
    return typed || null;
  }

  /**
   * Closes the panel and settles whoever was waiting.
   * @param {boolean} answer
   */
  close(answer) {
    this.toggleAttribute("data-open", false);
    removeEventListener("keydown", this.keys);
    this.settle?.(answer);
    this.settle = null;
  }
}

/* --- nx-viewer ---------------------------------------------------------- */

/**
 * NeXTSTEP's File Viewer, which is four bands stacked in one window.
 *
 * The shelf along the top keeps whatever is dropped on it and has nothing to
 * do with where you are. Under it one line of status about the whole. Then the
 * path, as a row of icons with an arrow between each pair. Then what the last
 * step of that path holds, in a scroller.
 *
 * It knows nothing about what it is showing. The page hands it a path and a
 * list of contents and listens for what was chosen, so the same component
 * serves machines, a shared directory, or anything else that is a place with
 * things in it.
 *
 * @attr status - The line under the shelf, where the page has nothing more
 *   particular to say.
 * @fires nx-path - A step of the path was chosen, carrying its index in
 *   `detail.index` and its value in `detail.value`.
 * @fires nx-choose - Something in the contents or on the shelf was chosen,
 *   from nx-thing, carrying its value.
 */
class NxViewer extends HTMLElement {
  connectedCallback() {
    if (this.ready) return;
    this.ready = true;

    this.keep = document.createElement("nx-shelf");
    this.keep.className = "keep";
    this.keep.addEventListener("dragover", (event) => {
      event.preventDefault();
      event.dataTransfer.dropEffect = "copy";
      this.keep.setAttribute("droppable", "");
    });
    this.keep.addEventListener("dragleave", (event) => {
      if (!this.keep.contains(event.relatedTarget)) this.keep.removeAttribute("droppable");
    });
    this.keep.addEventListener("drop", (event) => {
      event.preventDefault();
      this.keep.removeAttribute("droppable");
      this.dispatchEvent(new CustomEvent("nx-keep", {
        bubbles: true,
        detail: { value: event.dataTransfer.getData("text/plain") },
      }));
    });

    this.status = document.createElement("p");
    this.status.className = "status";
    this.status.textContent = this.getAttribute("status") ?? "";

    this.path = document.createElement("div");
    this.path.className = "path sunken";
    this.path.addEventListener("click", (event) => {
      const thing = event.target.closest("nx-thing");
      if (!thing || !this.path.contains(thing)) return;
      this.dispatchEvent(new CustomEvent("nx-path", {
        bubbles: true,
        detail: { index: Number(thing.dataset.step), value: thing.getAttribute("value") },
      }));
    });

    this.contents = document.createElement("nx-shelf");
    this.contents.className = "contents";
    const scroller = document.createElement("nx-scroller");
    scroller.append(this.contents);

    this.append(this.keep, this.status, this.path, scroller);
  }

  /**
   * Puts a place and its contents in the window.
   * @param {object} view
   * @param {Array<object>} view.path - The way here, outermost first. Each is
   *   `{label, icon, value}`.
   * @param {Array<object>} view.contents - What the last step holds. Each is
   *   `{label, icon, value}`, and `folder` marks one that has more inside.
   * @param {Array<object>} [view.keeps] - What lies on the shelf, the same
   *   shape. Left out, the shelf is not touched.
   * @param {string} [view.status] - The line under the shelf.
   */
  show({ path = [], contents = [], keeps, status }) {
    if (status !== undefined) this.status.textContent = status;
    if (keeps !== undefined) {
      this.keep.replaceChildren(...keeps.map((entry) => this.thing(entry)));
    }

    this.path.replaceChildren(...path.flatMap((step, index) => {
      const thing = this.thing(step);
      thing.dataset.step = String(index);
      /* The last step is where you are, and the shape that says so is the one
         a chosen thing already wears. */
      if (index === path.length - 1) thing.setAttribute("chosen", "");
      if (index === 0) return [thing];
      return [this.arrow(), thing];
    }));

    this.contents.replaceChildren(...contents.map((entry) => {
      const thing = this.thing(entry);
      if (entry.folder) thing.setAttribute("folder", "");
      return thing;
    }));
  }

  /**
   * @param {object} entry - `{label, icon, value}`.
   * @returns {HTMLElement} The icon with its name, ready to be appended.
   */
  thing(entry) {
    const thing = document.createElement("nx-thing");
    thing.setAttribute("icon", entry.icon ?? "");
    thing.setAttribute("label", entry.label ?? "");
    if (entry.value !== undefined) thing.setAttribute("value", entry.value);
    return thing;
  }

  /** @returns {HTMLElement} The mark between two steps of the path. */
  arrow() {
    const arrow = document.createElement("i");
    arrow.className = "step-arrow";
    return arrow;
  }
}

for (const [tag, type] of [
  ["nx-window", NxWindow],
  ["nx-menu", NxMenu],
  ["nx-menu-item", NxMenuItem],
  ["nx-tile", NxTile],
  ["nx-scroller", NxScroller],
  ["nx-shelf", NxShelf],
  ["nx-thing", NxThing],
  ["nx-ask", NxAsk],
  ["nx-viewer", NxViewer],
]) {
  customElements.define(tag, type);
}

/* After the definitions, because every window has to exist and know
   whether it is open before one of them can be picked out as the
   front one. */
restoreFront();
