"""What ships is what the sources say, and nothing of the workshop.

The three files in `web/` are generated, and a generated file that somebody
edits by hand is a change the next build throws away without saying so. This is
what says so, and it is also what holds the promise the whole arrangement is
for: the comments stay in `interface/` and reach nobody's browser.
"""

import importlib.util
import re
import shutil

import pytest

from conftest import INTERFACE
from previously.server import WEB_ROOT

#: The builder, loaded from where it lives rather than installed. It writes
#: nothing when it is imported.
BUILDER = INTERFACE.parent / "build_web.py"


@pytest.fixture(scope="module")
def build():
    spec = importlib.util.spec_from_file_location("build_web", BUILDER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def built(build, tmp_path_factory):
    """What the sources produce now, written somewhere of its own.

    Skipped where esbuild is absent, because then there is nothing to compare
    with rather than something that differs. The workflow installs it, so the
    comparison is made on every run that matters.
    """
    if shutil.which("esbuild") is None:
        pytest.skip("esbuild is not on this machine")
    return build.build(tmp_path_factory.mktemp("web"))


@pytest.fixture(scope="module")
def markup():
    return (WEB_ROOT / "index.html").read_text(encoding="utf-8")


def test_the_builder_is_where_the_tests_look_for_it():
    assert BUILDER.is_file()


@pytest.mark.parametrize("name", ["index.html", "previously.js", "previously.css"])
def test_what_is_served_is_what_the_sources_say(built, name):
    served = (WEB_ROOT / name).read_text(encoding="utf-8")

    assert served == built[name], "run make web"


def test_the_sources_are_not_served():
    """The whole point. A comment here is a paragraph about a decision, and it
    belongs to whoever edits this rather than to whoever loads it."""
    for name in ["app.js", "strings.js", "terminal.js", "nextstep.js",
                 "nextstep.css", "app.css", "lang"]:
        assert not (WEB_ROOT / name).exists(), name


def test_nothing_served_carries_a_comment_of_ours(built):
    """One line in the markup says where the files came from, and the vendor's
    license survives in the stylesheet because it has to. Everything else that
    looked like a comment was a note to ourselves."""
    assert built["index.html"].count("<!--") == 1
    assert "Built by admin/build_web.py" in built["index.html"]

    # The kit's own header is the longest comment in the script, so its absence
    # is the whole file's.
    assert "The NeXTSTEP kit" not in built["previously.js"]
    assert "Generated by design/build.py" not in built["previously.css"]


def test_the_vendor_license_survives_being_bundled(built):
    """Its MIT notice is a condition of using it, so it cannot be minified away
    with the rest of the comments."""
    assert "@license MIT" in built["previously.css"]
    assert (WEB_ROOT / "vendor" / "LICENSE").is_file()


def test_the_library_names_no_map():
    """Each of the two arrives with a `sourceMappingURL` at its foot, naming a
    map that is not vendored with it. Left on, every page load with the
    console open asks for it and is told 404. Held here, because an upgrade
    brings the line back and nothing else would say so."""
    for name in ["xterm.js", "xterm-addon-fit.js"]:
        text = (WEB_ROOT / "vendor" / name).read_text(encoding="utf-8")
        assert "sourceMappingURL" not in text, name


def test_the_page_asks_for_three_files(markup):
    """One stylesheet, the vendor library, and everything of ours."""
    assert re.findall(r'<link rel="stylesheet" href="([^"]+)"', markup) \
        == ["previously.css"]
    assert re.findall(r'<script src="([^"]+)"', markup) == [
        "vendor/xterm.js", "vendor/xterm-addon-fit.js", "previously.js"]


def test_the_library_is_loaded_before_what_uses_it(markup):
    """The terminal view is in our bundle and reaches for the library at the
    moment it is defined, so the order of those three tags is the page."""
    assert markup.index("vendor/xterm.js") < markup.index("previously.js")


def test_nothing_is_left_inline(markup):
    """The `translate()` call the markup used to carry is in the bundle now,
    between the catalogs and the kit, where it has to be."""
    assert "<script>" not in markup


def test_the_bundle_keeps_itself_to_itself(built):
    """Wrapped in a function, so no name in it is a global. Nothing outside
    needs one: the elements register themselves and every listener is added in
    code."""
    assert built["previously.js"].startswith("(()=>{")


def test_no_class_carries_two_rule_blocks():
    """One name, one thing, and one block that says what it looks like.

    The two stylesheets are concatenated into one, so a class declared in two
    places is a class whose appearance depends on which block was read last.
    Nothing warns: the element simply takes the wrong size, and whoever finds
    the first block has no reason to look for a second.

    Found on 2026-09-28, when `.module` was both a tile in the Preferences row
    and a memory module in a bank. The bank's block came second and handed the
    Preferences tiles its `width: 100%`, so a row of square icons stretched
    into two bars as wide as the window.
    """
    block = re.compile(r"([^{}]+)\{[^{}]*\}", re.DOTALL)
    comment = re.compile(r"/\*.*?\*/", re.DOTALL)
    simple = re.compile(r"^\.[a-zA-Z][\w-]*$")

    seen = {}
    for sheet in sorted(INTERFACE.glob("*.css")):
        text = comment.sub("", sheet.read_text(encoding="utf-8"))
        for rule in block.finditer(text):
            for selector in rule.group(1).split(","):
                selector = selector.strip()
                if simple.match(selector):
                    seen.setdefault(selector, []).append(sheet.name)

    twice = {name: sheets for name, sheets in seen.items() if len(sheets) > 1}

    assert twice == {}, f"declared more than once: {twice}"


def test_the_names_inside_are_shortened(built):
    """Which is what minifying with the names mangled means, and the reason
    nothing outside may reach in."""
    for name in ["askForPassword", "drawTheChoices", "editConfiguration"]:
        assert name not in built["previously.js"], name
