#!/usr/bin/env python3
"""Builds the icon sprite the website uses out of the two families it draws from.

The interface icons are Phosphor, in its duotone weight, and the one brand mark
is GitHub's own from Simple Icons. Both are fetched from their published
packages at a pinned version rather than copied in by hand, so the sprite can be
rebuilt and so the version each glyph came from is written down.

    python3 icons.py

It writes icons.svg beside itself. A page reaches a glyph through
<use href="site/icons.svg#copy">, and every path carries currentColor, so the
colour comes from whatever the icon sits in.
"""

import pathlib
import re
import urllib.request

HERE = pathlib.Path(__file__).parent
SPRITE = HERE / "icons.svg"

PHOSPHOR_VERSION = "2.1.1"
SIMPLE_ICONS_VERSION = "13.15.0"

# Which glyphs the page uses and what each one stands for, so a later reader
# does not have to open the page to find out whether one is still needed.
PHOSPHOR = {
    "cube": "the wordmark, which is a NeXTcube",
    "copy": "copies the install line",
    "check": "says the line has been copied",
    "monitor": "the screen, which shows NeXTSTEP and nothing else",
    "sliders-horizontal": "the admin tool, which configures the machine",
    "arrow-counter-clockwise": "every change the script makes can be undone",
    "terminal-window": "the shell the line is pasted into",
    "download-simple": "what the script fetches",
    "shield-check": "the script raises its own privileges and asks once",
    "arrow-square-out": "a link leaving this page",
}

BRAND = {
    "github": "the repository, whose mark is not an interface icon",
}

PHOSPHOR_URL = (
    "https://unpkg.com/@phosphor-icons/core@{version}/assets/duotone/{name}-duotone.svg"
)
SIMPLE_ICONS_URL = "https://unpkg.com/simple-icons@{version}/icons/{name}.svg"

# What a symbol keeps out of the file it came from. Everything else on the root
# element, such as the family's own xmlns and its fill, belongs to a standalone
# document rather than to a symbol inside one.
VIEWBOX = re.compile(r'viewBox="([^"]+)"')
BODY = re.compile(r"<svg[^>]*>(.*)</svg>", re.DOTALL)
TITLE = re.compile(r"<title>.*?</title>", re.DOTALL)


def fetch(url):
    """Returns the text of one SVG file, or raises if the version is wrong."""
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def symbol(name, source, purpose):
    """Turns one downloaded SVG into a <symbol> the page can reference.

    Two things are dropped from the file as it arrives. The title goes because
    a symbol used through <use> announces whatever the element around it says,
    and Simple Icons ships one naming the brand. The fill goes because a
    presentation attribute on the symbol beats what the page inherits into it,
    so a glyph carrying one cannot be recoloured or hidden from the stylesheet.
    site.css gives every icon `fill: currentcolor` in its place.
    """
    viewbox = VIEWBOX.search(source).group(1)
    body = BODY.search(source).group(1)
    body = TITLE.sub("", body).strip()
    return (
        f'  <!-- {purpose} -->\n'
        f'  <symbol id="{name}" viewBox="{viewbox}">\n'
        f'    {body}\n'
        f'  </symbol>'
    )


def main():
    symbols = []

    for name, purpose in PHOSPHOR.items():
        url = PHOSPHOR_URL.format(version=PHOSPHOR_VERSION, name=name)
        symbols.append(symbol(name, fetch(url), purpose))

    for name, purpose in BRAND.items():
        url = SIMPLE_ICONS_URL.format(version=SIMPLE_ICONS_VERSION, name=name)
        symbols.append(symbol(name, fetch(url), purpose))

    sprite = "\n".join(
        [
            "<!-- Generated by icons.py. Do not edit: add the glyph there and run it.",
            f"     Phosphor {PHOSPHOR_VERSION}, duotone, MIT.",
            f"     Simple Icons {SIMPLE_ICONS_VERSION}, CC0 1.0. -->",
            '<svg xmlns="http://www.w3.org/2000/svg" style="display: none">',
            *symbols,
            "</svg>",
            "",
        ]
    )
    SPRITE.write_text(sprite)
    print(f"{SPRITE.name}: {len(symbols)} symbols")


if __name__ == "__main__":
    main()
