#!/usr/bin/env python3
"""Bakes the bitmaps in parts/ into the mockup, so it stays one file.

The mockup carries a marker line in its :root block. Everything between that
marker and the next closing brace is replaced by one custom property per file
in parts/, each holding the picture as a data URI.

The pictures themselves come from two places, and extract.py puts them there:
the icons out of a NeXTSTEP 3.3 disk image, and the interface parts out of a
screenshot of the running system. Neither is drawn by hand, which is the whole
point of doing it this way.

    python3 build.py
"""

import base64
import pathlib
import re

HERE = pathlib.Path(__file__).parent
PARTS = HERE / "parts"
TARGET = HERE / "mockup-nextstep.html"
MARKER = "/* PARTS: generated by build.py, do not edit by hand */"


def data_uri(path):
    """@returns the file as a base64 data URI, ready for url()."""
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return 'url("data:image/png;base64,%s")' % encoded


def properties():
    """One custom property per picture, named after its file."""
    lines = [MARKER]
    for path in sorted(PARTS.glob("*.png")):
        lines.append("  --%s: %s;" % (path.stem, data_uri(path)))
    return "\n".join(lines)


def main():
    html = TARGET.read_text()
    pattern = re.compile(re.escape(MARKER) + r".*?(?=\n\})", re.DOTALL)
    if not pattern.search(html):
        raise SystemExit("marker not found in " + TARGET.name)
    TARGET.write_text(pattern.sub(lambda _: properties(), html))
    print("baked %d pictures into %s" % (len(list(PARTS.glob("*.png"))), TARGET.name))


if __name__ == "__main__":
    main()
