#!/usr/bin/env python3
"""Puts the kit together, and bakes the bitmaps into the mockup.

The kit is one source per component in kit/, each holding that component's
element and that component's styles beside it. This writes the two files the
admin serves out of them, and the same two into the mockup, so a component is
edited in one place and cannot drift from itself.

The pictures come from two places, and extract.py puts them there: the icons
out of a NeXTSTEP 3.3 disk image, and the interface parts out of a screenshot
of the running system. Into the mockup they go as data URIs, which is what
keeps it one file that opens anywhere.

    python3 build.py
"""

import base64
import pathlib
import re

HERE = pathlib.Path(__file__).parent
KIT = HERE / "kit"
PARTS = HERE / "parts"
MOCKUP = HERE / "mockup-nextstep.html"
SERVED = HERE.parent / "admin" / "web"

#: The kit, in the order its parts go together. Each entry names a source in
#: kit/, the custom elements that source defines, and what the part is for.
#:
#: The order is the order of the stylesheet and of the definitions alike, and
#: base stands first because the tokens and the two edges have to be there
#: before anything reads them. No two components name the same selector, so
#: beyond that the order is free.
KIT_PARTS = (
    ("base", (), "the tokens, the reset and the two edges"),
    ("desk", (), "what the desk remembers, and the gestures"),
    ("window", (("nx-window", "NxWindow"),),
     "a frame that drags, resizes, closes and remembers"),
    ("menu", (("nx-menu", "NxMenu"), ("nx-menu-item", "NxMenuItem")),
     "the menu, and the entries that open windows"),
    ("dock", (("nx-dock", "NxDock"), ("nx-tile", "NxTile"), ("nx-floor", "NxFloor")),
     "the column of tiles a person arranges, and the floor the others stand on"),
    ("scroller", (("nx-scroller", "NxScroller"),),
     "a view with NeXT's scroller on its left"),
    ("shelf", (("nx-shelf", "NxShelf"), ("nx-thing", "NxThing")),
     "a floor of icons, one of which may be chosen"),
    ("ask", (("nx-ask", "NxAsk"),), "the panel that asks before a change"),
    ("viewer", (("nx-viewer", "NxViewer"),),
     "the File Viewer, as four bands in one window"),
    ("panel", (), "nx-portrait, nx-row and nx-field, for an info panel"),
    ("terminal", (), "a text view, black on white"),
)

#: What every generated file says at the top, so nobody edits the wrong copy.
WRITTEN_BY = "Generated by design/build.py from design/kit/. Do not edit by hand."

#: Where the mockup takes the kit. Everything between each pair is written
#: here, and what the mockup has of its own stands outside them. The two pairs
#: differ, because one document holds both and a search for the wrong one would
#: write the script into the stylesheet.
MARKS = {
    "css": ("/* KIT STYLES: generated by build.py, do not edit by hand */",
            "/* END KIT STYLES */"),
    "js": ("/* KIT SCRIPT: generated by build.py, do not edit by hand */",
           "/* END KIT SCRIPT */"),
}

#: Where the pictures stand in base.css. In the mockup everything from this
#: line to the end of the block holding it is replaced by the same properties
#: carrying the pictures themselves, which is what keeps that file one file.
PARTS_MARKER = "/* PARTS: the pictures, which build.py bakes into the mockup as data URIs */"


def source(name, kind):
    """@returns the text of one part, or "" where it has none of that kind."""
    path = KIT / f"{name}.{kind}"
    return path.read_text() if path.exists() else ""


def stylesheet():
    """@returns the whole kit as one stylesheet."""
    blocks = [f"/* {WRITTEN_BY} */\n"]
    blocks += [source(name, "css") for name, _, _ in KIT_PARTS if source(name, "css")]
    return "\n".join(block.rstrip("\n") + "\n" for block in blocks)


def script():
    """@returns the whole kit as one script, with the definitions at its foot.

    The list of elements is written from the same table that orders the
    sources, so a part that is added is defined without anybody remembering to
    say so twice.
    """
    parts = [name for name, _, _ in KIT_PARTS if source(name, "js")]
    blocks = [overview()] + [source(name, "js") for name in parts]
    defined = [(tag, cls) for _, tags, _ in KIT_PARTS for tag, cls in tags]
    pairs = ",\n  ".join('["%s", %s]' % (tag, cls) for tag, cls in defined)
    blocks.append(
        "for (const [tag, type] of [\n  %s,\n]) {\n"
        "  customElements.define(tag, type);\n}\n"
        "\n"
        "/* After the definitions, because every window has to exist and know\n"
        "   whether it is open before one of them can be picked out as the\n"
        "   front one. */\n"
        "restoreFront();\n" % pairs)
    return "\n".join(block.rstrip("\n") + "\n" for block in blocks)


def overview():
    """@returns the comment at the head of the script, listing what is in it.

    Written from the table rather than kept beside it, because a list of the
    parts that somebody has to remember to correct is a list that goes wrong.
    """
    width = max(len(", ".join(tag for tag, _ in tags) or name)
                for name, tags, _ in KIT_PARTS)
    lines = ["/* The NeXTSTEP kit: everything the interface is built from.",
             " *",
             f" * {WRITTEN_BY}",
             " *",
             " * Each part is one source in design/kit/, holding its element and its",
             " * styles together:",
             " *"]
    for name, tags, says in KIT_PARTS:
        shown = ", ".join(tag for tag, _ in tags) or name
        lines.append(" *   %-*s  %s" % (width, shown, says))
    lines += [" *",
              " * They use the light DOM rather than a shadow root, so the stylesheet",
              " * reaches them and the design tokens carry through.",
              " */"]
    return "\n".join(lines) + "\n"


def data_uri(path):
    """@returns the file as a base64 data URI, ready for url()."""
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return 'url("data:image/png;base64,%s")' % encoded


def properties():
    """One custom property per picture, named after its file."""
    lines = [PARTS_MARKER]
    for path in sorted(PARTS.glob("*.png")):
        lines.append("  --%s: %s;" % (path.stem, data_uri(path)))
    return "\n".join(lines)


def between(text, marks, block, what):
    """Replaces what stands between a pair of marks.

    @param text - The whole document.
    @param marks - The opening and closing lines.
    @param block - What to put between them.
    @param what - The name of the document, for the complaint.
    @returns str
    """
    opening, closing = marks
    pattern = re.compile(re.escape(opening) + r".*?" + re.escape(closing), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"{what} has no {opening} ... {closing}")
    return pattern.sub(lambda _: opening + "\n" + block + closing, text)


def main():
    css = stylesheet()
    js = script()

    html = MOCKUP.read_text()
    html = between(html, MARKS["css"], css, MOCKUP.name)
    html = between(html, MARKS["js"], js, MOCKUP.name)
    # The pictures last, because the block they go in has just been written.
    pattern = re.compile(re.escape(PARTS_MARKER) + r".*?(?=\n\})", re.DOTALL)
    if not pattern.search(html):
        raise SystemExit("no " + PARTS_MARKER + " in " + MOCKUP.name)
    html = pattern.sub(lambda _: properties(), html)

    # Everything is written at the end, so a run that cannot finish leaves all
    # three as they were rather than two of them half done.
    (SERVED / "nextstep.css").write_text(css)
    (SERVED / "nextstep.js").write_text(js)
    MOCKUP.write_text(html)

    print("wrote %d lines of stylesheet and %d of script from %d parts, "
          "and baked %d pictures into %s"
          % (len(css.splitlines()), len(js.splitlines()), len(KIT_PARTS),
             len(list(PARTS.glob("*.png"))), MOCKUP.name))


if __name__ == "__main__":
    main()
